#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Récupérer tous les fichiers modifiés qui ne sont pas supprimés
files=$(git diff --cached --name-only --diff-filter=d)

for file in $files; do
    # Vérifier si le fichier contient "var_dump"
    if grep -q "var_dump" "$file"; then
        echo "❌ ERREUR : Le fichier '$file' contient un 'var_dump'."
        echo "Supprimez tous les 'var_dump' avant de pousser votre code."
        exit 1
    fi
done

echo "✅ Aucun 'var_dump' détecté. Poussée autorisée."
exit 0
